# Generated by Django 6.0.5 on 2026-05-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
        migrations.AddField(
            model_name="project",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
        migrations.AddField(
            model_name="project",
            name="is_confidential",
            field=models.BooleanField(
                default=False, help_text="Hides source code / sensitive info"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="users_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Live users / customers (optional)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="users_count_label",
            field=models.CharField(
                blank=True, help_text="e.g. '+3 today'", max_length=80
            ),
        ),
    ]
